name: Sync origin dev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0
          persist-credentials: false

      - name: Login GitHub as me
        run: |
          gh auth status
          gh auth setup-git

      - name: Configure origin
        run: |
          git remote set-url origin https://github.com/AI20K-Build-Phase-Cohort-3/P-141.git
          git remote set-url --push origin https://github.com/tuananhpham-vnu/VmedTriage_MicroGenius.git
          git remote -v

      - name: Sync dev
        run: |
          git fetch origin dev
          git checkout dev
          git reset --hard origin/dev
          git clean -fd
          git push origin dev --force
